# Generated by Django 4.1.7 on 2023-05-30 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8e88c0a4-354e-49e4-bd22-c20a4744cec6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
